updates

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -41,25 +41,25 @@
 initialize() {
 	require_git_repo
 	require_gitflow_initialized
-	git config --get gitflow.prefix.feature >/dev/null 2>&1 || die "Feature prefix not set. Please run 'git flow init'."
+	git config --get gitflow.prefix.feature >/dev/null 2>&1 || die "Feature prefix not set. Please run 'igit init'."
 	gitflow_load_settings
 	PREFIX=$(git config --get gitflow.prefix.feature)
 }
 
 usage() {
 	OPTIONS_SPEC="\
-git flow feature [list]
-git flow feature start
-git flow feature finish
-git flow feature publish
-git flow feature track
-git flow feature diff
-git flow feature rebase
-git flow feature checkout
-git flow feature pull
-git flow feature delete
-git flow feature rename
-git flow feature release
+igit feature [list]
+igit feature start
+igit feature finish
+igit feature publish
+igit feature track
+igit feature diff
+igit feature rebase
+igit feature checkout
+igit feature pull
+igit feature delete
+igit feature rename
+igit feature release
 
 Manage your feature branches.
 
@@ -75,7 +75,7 @@ cmd_default() {
 
 cmd_list() {
 	OPTIONS_SPEC="\
-git flow feature [list] [-h] [-v]
+igit feature [list] [-h] [-v]
 
 Lists all the existing feature branches in the local repository.
 --
@@ -97,7 +97,7 @@ v,verbose   Verbose (more) output
 		warn ""
 		warn "You can start a new feature branch:"
 		warn ""
-		warn "    git flow feature start <name> [<base>]"
+		warn "    igit feature start <name> [<base>]"
 		warn ""
 		exit 0
 	fi
@@ -179,7 +179,7 @@ parse_remote_name() {
 
 cmd_start() {
 	OPTIONS_SPEC="\
-git flow feature start [-h] [-F] <name> [<base>]
+igit feature start [-h] [-F] <name> [<base>]
 
 Start new feature <name>, optionally basing it on <base> instead of <develop>
 --
@@ -233,13 +233,13 @@ F,[no]fetch      Fetch from origin before performing local operation
 	echo ""
 	echo "Now, start committing on your feature. When done, use:"
 	echo ""
-	echo "     git flow feature finish $NAME"
+	echo "     igit feature finish $NAME"
 	echo
 }
 
 cmd_finish() {
 	OPTIONS_SPEC="\
-git flow feature finish [-h] [-F] [-r] [-p] [-k] [-D] [-S] [--no-ff] <name|nameprefix>
+igit feature finish [-h] [-F] [-r] [-p] [-k] [-D] [-S] [--no-ff] <name|nameprefix>
 
 Finish feature <name>
 --
@@ -339,7 +339,7 @@ no-ff!                 Never fast-forward during the merge
 			echo "    git commit"
 			echo
 			echo "You can then complete the finish by running it again:"
-			echo "    git flow feature finish $NAME"
+			echo "    igit feature finish $NAME"
 			echo
 			exit 1
 		fi
@@ -379,11 +379,11 @@ no-ff!                 Never fast-forward during the merge
 		if flag showcommands; then
 			_rebase_opts="$_rebase_opts --showcommands"
 		fi
-		if ! git flow feature rebase $_rebase_opts "$NAME"; then
+		if ! igit feature rebase $_rebase_opts "$NAME"; then
 			warn "Finish was aborted due to conflicts during rebase."
 			warn "Please finish the rebase manually now."
 			warn "When finished, re-run:"
-			warn "    git flow feature finish '$NAME' '$BASE_BRANCH'"
+			warn "    igit feature finish '$NAME' '$BASE_BRANCH'"
 			exit 1
 		fi
 	fi
@@ -419,7 +419,7 @@ no-ff!                 Never fast-forward during the merge
 		echo "    git commit"
 		echo
 		echo "You can then complete the finish by running it again:"
-		echo "    git flow feature finish $NAME"
+		echo "    igit feature finish $NAME"
 		echo
 		exit 1
 	fi
@@ -433,7 +433,7 @@ no-ff!                 Never fast-forward during the merge
 
 cmd_release() {
 	OPTIONS_SPEC="\
-git flow feature release [-h]
+igit feature release [-h]
 
 Create a release based on current feature
 --
@@ -472,7 +472,13 @@ helper_finish_cleanup() {
 	localbranchdeleted=$FLAGS_FALSE
 
 	if flag push; then
-		git_do push --force-with-lease --force-if-includes "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
+		access_token=$(git config --get gitflow.token)
+		if [ -n "$access_token" ]; then
+			echo "Pushing with access token"
+			GIT_URL=$(git config --get remote.origin.url)
+			ORIGIN="${GIT_URL/\:\/\//://$access_token@}"
+		fi
+		git_do push "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
 	fi
 
 	if noflag keep; then
@@ -534,7 +540,7 @@ helper_finish_cleanup() {
 
 cmd_publish() {
 	OPTIONS_SPEC="\
-git flow feature publish [-h] [<name>]
+igit feature publish [-h] [<name>]
 
 Publish feature branch <name> on $ORIGIN.
 When <name> is omitted the current branch is used, but only if it's a feature branch.
@@ -576,7 +582,7 @@ showcommands!    Show git commands while executing them
 
 cmd_track() {
 	OPTIONS_SPEC="\
-git flow feature track [-h] <name>
+igit feature track [-h] <name>
 
 Start tracking feature <name> that is shared on $ORIGIN
 --
@@ -611,7 +617,7 @@ showcommands!    Show git commands while executing them
 
 cmd_diff() {
 	OPTIONS_SPEC="\
-git flow feature diff [-h] [<name|nameprefix>]
+igit feature diff [-h] [<name|nameprefix>]
 
 Show all changes in <name> that are not in the base
 --
@@ -636,7 +642,7 @@ showcommands!    Show git commands while executing them
 
 cmd_checkout() {
 	OPTIONS_SPEC="\
-git flow feature checkout [-h] [<name|nameprefix>]
+igit feature checkout [-h] [<name|nameprefix>]
 
 Switch to feature branch <name>
 --
@@ -660,7 +666,7 @@ cmd_co() {
 
 cmd_rebase() {
 	OPTIONS_SPEC="\
-git flow feature rebase [-h] [-i] [-p] [<name|nameprefix>]
+igit feature rebase [-h] [-i] [-p] [<name|nameprefix>]
 
 Rebase <name> on <base_branch>
 --
@@ -724,7 +730,7 @@ avoid_accidental_cross_branch_action() {
 
 cmd_pull() {
 	OPTIONS_SPEC="\
-git flow feature pull [-h] <remote> [<name>]
+igit feature pull [-h] <remote> [<name>]
 
 Pull feature <name> from <remote>
 --
@@ -736,7 +742,7 @@ showcommands!    Show git commands while executing them
 	# Define flags
 	DEFINE_boolean 'rebase' false "pull with rebase" r
 
-	warn "The command 'git flow feature pull' will be deprecated per version 2.0.0. Use 'git flow feature track' instead."
+	warn "The command 'igit feature pull' will be deprecated per version 2.0.0. Use 'igit feature track' instead."
 
 	# Parse arguments
 	parse_remote_name "$@"
@@ -793,7 +799,7 @@ showcommands!    Show git commands while executing them
 
 cmd_delete() {
 	OPTIONS_SPEC="\
-git flow feature delete [-h] [-f] [-r] <name>
+igit feature delete [-h] [-f] [-r] <name>
 
 Delete a given feature branch
 --
@@ -865,7 +871,7 @@ r,[no]remote     Delete remote branch
 
 cmd_rename() {
 	OPTIONS_SPEC="\
-git flow feature rename [<old_name>] <new_name>
+igit feature rename [<old_name>] <new_name>
 
 Rename a given feature branch
 --
diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -41,7 +41,7 @@
 initialize() {
 	require_git_repo
 	require_gitflow_initialized
-	git config --get gitflow.prefix.hotfix >/dev/null 2>&1 || die "Hotfix prefix not set. Please run 'git flow init'."
+	git config --get gitflow.prefix.hotfix >/dev/null 2>&1 || die "Hotfix prefix not set. Please run 'igit init'."
 	gitflow_load_settings
 	VERSION_PREFIX=$(git config --get gitflow.prefix.versiontag)
 	PREFIX=$(git config --get gitflow.prefix.hotfix)
@@ -49,14 +49,14 @@ initialize() {
 
 usage() {
 	OPTIONS_SPEC="\
-git flow hotfix [list]
-git flow hotfix start
-git flow hotfix finish
-git flow hotfix publish
-git flow hotfix delete
-git flow hotfix rebase
-git flow hotfix track
-git flow hotfix rename
+igit hotfix [list]
+igit hotfix start
+igit hotfix finish
+igit hotfix publish
+igit hotfix delete
+igit hotfix rebase
+igit hotfix track
+igit hotfix rename
 
 Manage your hotfix branches.
 
@@ -72,7 +72,7 @@ cmd_default() {
 
 cmd_list() {
 	OPTIONS_SPEC="\
-git flow hotfix [list] [-h] [-v]
+igit hotfix [list] [-h] [-v]
 
 Lists all local hotfix branches
 --
@@ -94,7 +94,7 @@ v,verbose!        Verbose (more) output
 		warn ""
 		warn "You can start a new hotfix branch:"
 		warn ""
-		warn "    git flow hotfix start <version> [<base>]"
+		warn "    igit hotfix start <version> [<base>]"
 		warn ""
 		exit 0
 	fi
@@ -170,7 +170,7 @@ require_no_existing_hotfix_branches() {
 
 cmd_start() {
 	OPTIONS_SPEC="\
-git flow hotfix start [-h] [-F] <version> [<base>]
+igit hotfix start [-h] [-F] <version> [<base>]
 
 Start new hotfix branch named <version>, optionally base it on <base> instead of the <master> branch
 --
@@ -240,13 +240,13 @@ F,[no]fetch       Fetch from origin before performing local operation
 	echo "- Bump the version number now!"
 	echo "- When done, run:"
 	echo
-	echo "     git flow hotfix finish '$VERSION'"
+	echo "     igit hotfix finish '$VERSION'"
 	echo
 }
 
 cmd_publish() {
 	OPTIONS_SPEC="\
-git flow hotfix publish [-h] <version>
+igit hotfix publish [-h] <version>
 
 Start sharing hotfix <name> on $ORIGIN
 --
@@ -286,7 +286,7 @@ showcommands!     Show git commands while executing them
 
 cmd_rebase() {
 	OPTIONS_SPEC="\
-git flow hotfix rebase [-h] [-i] [-p] [<name|nameprefix>]
+igit hotfix rebase [-h] [-i] [-p] [<name|nameprefix>]
 
 Rebase <name> on <base_branch>
 --
@@ -336,7 +336,7 @@ p,[no]preserve-merges  Preserve merges
 
 cmd_track() {
 	OPTIONS_SPEC="\
-git flow hotfix track [-h] <version>
+igit hotfix track [-h] <version>
 
 Create a tracking hotfix branch from $ORIGIN
 --
@@ -367,7 +367,7 @@ showcommands!     Show git commands while executing them
 
 cmd_finish() {
 	OPTIONS_SPEC="\
-git flow hotfix finish [-h] [-F] [-s] [-u] [-m | -f ] [-p] [-k] [-n] [-b | -c | -r] [-S] <version>
+igit hotfix finish [-h] [-F] [-s] [-u] [-m | -f ] [-p] [-k] [-n] [-b | -c | -r] [-S] <version>
 
 Finish hotfix branch <version>
 --
@@ -562,7 +562,7 @@ if flag cherrypick; then
 =    *** If fixing the conflict results in an empty commit,
 =        you will need to run this command: 'git commit --allow-empty'
 = 4. Switch back to the hotfix branch: 'git checkout $BRANCH'
-= 5. Rerun the finish command: 'git flow hotfix finish'
+= 5. Rerun the finish command: 'igit hotfix finish'
 = OR run 'git cherry-pick --abort' to abort the cherry pick
 ===============================================================\n"
 		                        die "Cherry pick failed for commit: $commit_hash"
@@ -665,15 +665,22 @@ if flag cherrypick; then
 	run_post_hook "$VERSION_PREFIX$TAGNAME" "$ORIGIN" "$BRANCH"
 
 	if flag push; then
+		access_token=$(git config --get gitflow.token)
+		if [ -n "$access_token" ]; then
+			echo "Pushing with access token"
+			GIT_URL=$(git config --get remote.origin.url)
+			ORIGIN="${GIT_URL/\:\/\//://$access_token@}"
+		fi
+
 		if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
-			git_do push --force-with-lease --force-if-includes "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
+			git_do push "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
 		fi
 		if [ -n "$release_branch" ]; then
-		  git_do push --force-with-lease --force-if-includes "$ORIGIN" "$release_branch" || dir "Could not push branch '$release_branch' to remote '$ORIGIN'."
+		  git_do push "$ORIGIN" "$release_branch" || dir "Could not push branch '$release_branch' to remote '$ORIGIN'."
 		fi
-		git_do push --force-with-lease --force-if-includes "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
+		git_do push "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
 		if noflag notag; then
-			git_do push --force-with-lease --force-if-includes --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
+			git_do push "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
 		fi
 	fi
 
@@ -756,7 +763,7 @@ if flag cherrypick; then
 
 cmd_delete() {
 	OPTIONS_SPEC="\
-git flow hotfix delete [-h] [-f] [-r] <name>
+igit hotfix delete [-h] [-f] [-r] <name>
 
 Delete the given hotfix branch
 --
@@ -821,7 +828,7 @@ r,[no]remote          Delete remote branch
 
 cmd_rename() {
 	OPTIONS_SPEC="\
-git flow hotfix rename [<old_name>] <new_name>
+igit hotfix rename [<old_name>] <new_name>
 
 Rename a given hotfix branch
 --
