updates

diff --git a/git-flow-stage b/git-flow-stage
--- a/git-flow-stage
+++ b/git-flow-stage
@@ -191,17 +191,17 @@ _finish_from_develop() {
 		if [ -n "$access_token" ]; then
 			echo "Pushing with access token"
 			GIT_URL=$(git config --get remote.origin.url)
-			ORIGIN="${GIT_URL/\:\/\//://$access_token@}"
+			WITH_TOKEN="${GIT_URL/\:\/\//://$access_token@}"
 		fi
 
 		if flag pushdevelop; then
-			git_do push "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
+			git_do push "$WITH_TOKEN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
 		fi
 		if flag pushproduction; then
-			git_do push "$ORIGIN" "$MASTER_BRANCH" || die "Could not push branch '$MASTER_BRANCH' to remote '$ORIGIN'."
+			git_do push "$WITH_TOKEN" "$MASTER_BRANCH" || die "Could not push branch '$MASTER_BRANCH' to remote '$ORIGIN'."
 		fi
 		if noflag notag && flag pushtag; then
-			git_do push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
+			git_do push --tags "$WITH_TOKEN" || die "Could not push tags to remote '$ORIGIN'."
 		fi
 	fi
 
@@ -212,11 +212,10 @@ _finish_from_develop() {
 			git_do checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
 		fi
 
-		# Always delete remote first
-		if noflag keepremote;then
-			if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
-				git_remote_branch_delete "$BRANCH" && remotebranchdeleted=$FLAGS_TRUE
-			fi
+		echo "git_remote_branch_exists: $ORIGIN/$BRANCH"
+		if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+			echo "git_remote_branch_exists oooo: $ORIGIN/$BRANCH"
+			git_remote_branch_delete "$BRANCH" && remotebranchdeleted=$FLAGS_TRUE
 		fi
 
 		# Delete local after remote to avoid warnings
