updates

diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -149,11 +149,12 @@ parse_args() {
 	eval set -- "${FLAGS_ARGV}"
 
 	# Read arguments into global variables
-	if [ -z $1 ]; then
-		VERSION=''
-	else
-		VERSION=$1
-	fi
+	VERSION=$(git_next_hoxfix_tag)
+	# if [ -z $1 ]; then
+	# 	VERSION=''
+	# else
+	# 	VERSION=$1
+	# fi
 	BRANCH=$PREFIX$VERSION
 }
 
@@ -240,6 +241,33 @@ F,[no]fetch       Fetch from origin before performing local operation
 	echo "- When done, run:"
 	echo
 	echo "     git flow hotfix finish '$VERSION'"
+	echo
+
+		# Use current branch if no version is given
+	if [ "$VERSION" = "" ]; then
+		gitflow_use_current_branch_version
+	fi
+
+	# Sanity checks
+	require_clean_working_tree
+	require_branch "$BRANCH"
+	git_do fetch -q "$ORIGIN" || die "Could not fetch branch '$BRANCH' from remote '$ORIGIN'."
+	require_branch_absent "$ORIGIN/$BRANCH"
+
+	run_pre_hook "$VERSION_PREFIX$VERSION" "$ORIGIN" "$BRANCH"
+
+	# Create remote branch with remote tracking
+	git_do push -u "$ORIGIN" "$BRANCH:$BRANCH"
+	git_do fetch -q "$ORIGIN" "$BRANCH" || die "Could not fetch branch '$BRANCH' from remote '$ORIGIN'."
+	git_do checkout "$BRANCH" || die "Could not check out branch '$BRANCH'."
+
+	run_post_hook "$VERSION_PREFIX$VERSION" "$ORIGIN" "$BRANCH"
+
+	echo
+	echo "Summary of actions:"
+	echo "- The remote branch '$BRANCH' was created or updated"
+	echo "- The local branch '$BRANCH' was configured to track the remote branch"
+	echo "- You are now on branch '$(git_current_branch)'"
 	echo
 }
 
@@ -397,7 +425,7 @@ c,cherrypick          Cherry Pick to $DEVELOP_BRANCH instead of merge
 	DEFINE_string  'signingkey' "" "use the given GPG-key for the digital signature (implies -s)" u
 	DEFINE_string  'message' "" "use the given tag message" m
 	DEFINE_string  'messagefile' "" "use the contents of the given file as tag message" f
-	DEFINE_boolean 'push' false "push to $ORIGIN after performing finish" p
+	DEFINE_boolean 'push' true "push to $ORIGIN after performing finish" p
 	DEFINE_boolean 'keep' false "keep branch after performing finish" k
 	DEFINE_boolean 'keepremote' false "keep the remote branch"
 	DEFINE_boolean 'keeplocal' false "keep the local branch"
@@ -437,11 +465,15 @@ c,cherrypick          Cherry Pick to $DEVELOP_BRANCH instead of merge
 	fi
 
 	# Use branch name if no tag name is given
-	if [ "$FLAGS_tagname" != "" ]; then
-		TAGNAME=$FLAGS_tagname
-	else
-		TAGNAME=$VERSION
-	fi
+	
+	TAGNAME=$(git_next_hoxfix_tag)
+	echo "TAGNAME: $TAGNAME"
+
+	# if [ "$FLAGS_tagname" != "" ]; then
+	# 	TAGNAME=$FLAGS_tagname
+	# else
+	# 	TAGNAME=$VERSION
+	# fi
 
 	remotebranchdeleted=$FLAGS_FALSE
 	localbranchdeleted=$FLAGS_FALSE
